Update logging levels to uppercase strings
CDOT-CV/asn1_codec pull request #13
Opened 2023-07-18 18:48 UTC by mwodahl

Updates ACM logging parameters to use uppercase strings

2023-07-18 19:26 UTC, dmccoystephenson requested changes

2023-07-18 19:26 UTC, dmccoystephenson commented on sample.env
> +# Valid values are: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "off"
"off" should be capitalized here

2023-07-18 19:30 UTC, mwodahl commented on sample.env
> +# Valid values are: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "off"
Updated to capitalize 'off'

2023-07-18 19:35 UTC, dmccoystephenson approved these changes
Looks good!

2023-07-24 17:21 UTC, payneBrandon approved these changes

2023-07-24 17:22 UTC, merged