Transition to J2735 ASN 2020
CDOT-CV/asn1_codec pull request #19
Opened 2023-12-14 22:12 UTC by dmccoystephenson

# Transition to 2020
The ACM has transitioned to using the 2020 version of the J2735 ASN specification for compiling header and implementation files essential for message processing.

## Updated ASN.1 Compiler Repository
We have adopted Leidos' fork of the ASN.1 Compiler, accessible at https://www.github.com/mouse07410/asn1c. This change was necessary due to the 'WITH SUCCESSORS' keyword in the 2020 J2735 ASN specification, which is not supported by the original repository (https://www.github.com/vlm/asn1c) currently.

Adjustments to the dockerfiles were made to accommodate this switch.

## Modifications to doIt.sh Script
The doIt.sh script now directs to the 'asn1c_combined/j2735-asn-files/2020' directory, utilizing all *.asn files in that directory as input for the ASN.1 Compiler.

## SEMI ASN File Updates
The SEMI file has been updated to be compatible with J2735 2020. Structure references had to be changed and import statements were added.

This file has been renamed to differentiate it from the previous version of the file.

The changelog included at the top of the file has been updated, including the following:
- When the file was last updated
- Who updated the file last and what company they work for (this followed the convention already present)
- What got updated

## Unit Tests
Three new unit tests have been introduced for encoding TIMs with OdeTimPayload/OdeAsdPayload payload types and decoding a BSM. Each unit test is now encapsulated within its own TEST_CASE instead of being grouped under a single TEST_CASE.

Unit tests associated with encoding BSMs have been commented out, as they are not a desired feature of the ACM and were failing after the transition to mouse07410/asn1c.

## Testing
BSM Decoding & TIM Encoding have been verified to be working through manual testing. This involved spinning up the ACM & sending data to the relevant kafka topics.

## ODE Updates
The ODE will need to be updated to be compatible with J2735 2020. This work should be done before the merging of this PR.

2024-01-10 17:20 UTC, drewjj commented on .gitmodules
> +[submodule "asn1c"]
Are there changes in this mouse07410 fork for the asn1c repository? If so, we may want to consider creating a USODT fork of this in the future.

2024-01-10 22:47 UTC, dmccoystephenson commented on .gitmodules
> +[submodule "asn1c"]
Yes, the mouse07410 fork has diverged somewhat from the original asn1c repository. Some of the support that it has is necessary for this update.

The mouse07410 fork appears to be getting updated continuously. Were we to create a USDOT fork, we'd have to pull any new changes in manually via a PR rather than just updating the git submodule commit references. Might be good, though!

2024-01-11 00:01 UTC, dmccoystephenson commented
The alpine image updates were merged into the `j2735/transition-to-2020` branch. This will require some changes to the dockerfiles and further testing. Marking this as a draft for now.

2024-01-11 16:19 UTC, dmccoystephenson commented on src/acm.cpp
> + * This method assumes that the data being checked is a J2735 MessageFrame.
The clarity of this conformance check has been improved. That is correct, but we will not be supporting prior versions of J2735.

2024-01-11 20:47 UTC, dmccoystephenson commented
The dockerfiles have been updated to be compatible with alpine linux. This is once again ready for review.

2024-01-12 17:17 UTC, drewjj commented on .gitmodules
> +[submodule "asn1c"]
The guy who's fork that is works for Leidos. What I mean is to also have them stop working on their own private fork.

2024-01-12 17:21 UTC, drewjj commented on src/acm.cpp
> + * This method assumes that the data being checked is a J2735 MessageFrame.
If it isn't supported I fail to understand why we are including the 2016 as an option in the repository?

2024-01-12 17:21 UTC, drewjj commented on src/acm.cpp
> + * This method assumes that the data being checked is a J2735 MessageFrame.
Might as well not even have flexibility

2024-01-12 17:47 UTC, drewjj requested changes
I would like to see this be more flexible with a configuration change. You say we aren't supporting 2016 but I am challenging that. If we would like to discuss this further please let me know.

2024-01-12 17:52 UTC, drewjj approved these changes
Aight, I've been asked to approve this. Please make a backlog ticket for flexible support for all standards. Not just newer, but older versions.

2024-01-12 18:12 UTC, dmccoystephenson commented on src/acm.cpp
> + * This method assumes that the data being checked is a J2735 MessageFrame.
That's true. Were we to not support multiple versions, the added flexibility to the `doIt.sh` script wouldn't be necessary.

2024-01-12 18:13 UTC, dmccoystephenson commented on .gitmodules
> +[submodule "asn1c"]
It would make sense for Leidos to work on a USDOT fork of the asn1c repository.

2024-01-15 18:20 UTC, mwodahl approved these changes
This looks good and runs locally for me!

2024-01-16 20:55 UTC, dmccoystephenson commented on Dockerfile
> +    flex \
These appear to be required to build the `mouse07140/asn1c`.

2024-01-16 20:59 UTC, dmccoystephenson commented on asn1c_combined/doIt.sh
> +asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all \
Looks like `-gen-PER` is invalid argument when using `mouse07410/asn1c`.

According to mouse07410, the 'vlm_master' branch of his fork enables PER by default. This is the default branch, also.
(source: https://github.com/mouse07410/asn1c/issues/33#issuecomment-372696077)

2024-01-16 21:50 UTC, dmccoystephenson commented
Redistributing the ASN files is not permitted, so they have been removed & the README has been updated to direct the developer to obtain them independently.

2024-01-16 23:43 UTC, payneBrandon approved these changes
lgtm!

2024-01-16 23:43 UTC, merged