Include Generated Header/Implementation Files
CDOT-CV/asn1_codec pull request #21
Opened 2024-01-19 19:54 UTC by dmccoystephenson

## Problem
We recently removed the J2735 ASN files as we are not permitted to redistribute them. This has caused the travis build to start failing as it is unable to generate the necessary C files at build time.

## Solution
The generated header/implementation files for 2016 & 2020 have been included in the project in compressed form.

The generation part of the `doIt.sh` script has been moved to the `generate-files.sh` script. The `doIt.sh` script is now responsible for retrieving the proper files & extracting them into the `asn1c_combined` directory.

## Testing
- The project is able to built & run with these changes using Docker.
- The unit tests pass.
- Running a message through the program in AEM mode has been verified to be processed successfully.

2024-01-19 21:51 UTC, drewjj approved these changes
This looks great. It tested fine locally.

2024-01-24 16:49 UTC, mwodahl approved these changes
This looks good! It ran correctly locally

2024-01-26 22:15 UTC, payneBrandon commented on Dockerfile
> +RUN rm -rf /asn1c_codec/asn1c_combined/j2735-asn-files
These should already be removed right? Do we need this?

2024-01-26 22:19 UTC, payneBrandon commented on asn1c_combined/generate-files.sh
> +# This script generates the J2735 files for a given year.
This script relies on the asn files being available in the solution, right? Should we add a comment in here to that effect?

2024-01-26 22:21 UTC, payneBrandon commented on asn1c_combined/generate-files.sh
> +# This script generates the J2735 files for a given year.
Looks like that's well-covered in the README, disregard

2024-01-26 22:21 UTC, payneBrandon requested changes
Just the one question on necessity of removing files

2024-01-26 22:33 UTC, dmccoystephenson commented on Dockerfile
> +RUN rm -rf /asn1c_codec/asn1c_combined/j2735-asn-files
If the user has any ASN files in the `asn1c_combined/j2735-asn-files` directory at build time, they will be added to the image on line 34:
> ADD ./asn1c_combined /asn1_codec/asn1c_combined

In the event that the user has just regenerated the implementation/header files using the `generate-files.sh` script files, this ensures that the ASN files the script references in the 'j2735-asn-files' directory don't make it into the image.

2024-01-26 22:35 UTC, payneBrandon approved these changes
lgtm!

2024-01-26 22:35 UTC, merged