Confluent Cloud Integration
CDOT-CV/asn1_codec pull request #3
Opened 2022-02-17 19:11 UTC by dmccoystephenson

2022-02-25 19:12 UTC, dmccoystephenson commented
These changes have been tested to be backwards compatible. When the KAFKA_TYPE environment variable is not set or is set to something other than "CONFLUENT", the ACM will attempt to work with a local kafka instance as usual.

2022-02-25 19:39 UTC, payneBrandon requested changes
Looks good, just a few comments. Along with the migration to an installed librdkafka instance, we should remove the librdkafa submodule so there's no confusion.

2022-02-25 19:39 UTC, payneBrandon commented on Dockerfile
> +RUN apt-get install -y libsasl2-dev
Let's combine these into a single "RUN" command to make this a bit cleaner

2022-02-25 19:39 UTC, payneBrandon commented on Dockerfile
>  #RUN apt-get update && apt-get install -y nano
If we're not using the vim/nano tools, let's remove from the Dockerfile while we're in here

2022-02-25 19:39 UTC, payneBrandon commented on docker-compose-confluent-cloud.yml
> +version: '2'
Let's format this in the same way as the other docker-compose.yml file, which spins up the standalone version along with a Kafka image. Then when we create a PR to the main USDOT repo we can include documentation on spinning up multiple containers targeting Confluent. 

Currently, these services are set to depend on "kafka" image which doesn't exist within this yml file.

2022-02-25 19:39 UTC, payneBrandon commented on src/acm.cpp
> +    // std::cout << "The topic_available() method has finished executing. Return value: " << r << std::endl;
Let's clean out this commented statement

2022-02-25 19:39 UTC, payneBrandon commented on src/acm.cpp
> +        std::cout << "Something went wrong attempting to retrieve the environment variable " << variableName << std::endl;
Let's throw this to the logger rather than cout, error level.

2022-02-25 19:39 UTC, payneBrandon commented on src/acm.cpp
> +        // conf->set("debug", "all", error_string);
Let's remove.

2022-02-25 19:39 UTC, payneBrandon commented on src/acm.cpp
> +    // print_configuration();
Let's remove

2022-02-25 21:50 UTC, dmccoystephenson commented on src/acm.cpp
> +        std::cout << "Something went wrong attempting to retrieve the environment variable " << variableName << std::endl;
This method has been moved to the ASN1_Codec class so the internal logger could be utilized.

2022-02-25 22:25 UTC, dmccoystephenson commented on Dockerfile
> +RUN apt-get install -y libsasl2-dev
These commands have been combined.

2022-02-25 22:25 UTC, dmccoystephenson commented on Dockerfile
>  #RUN apt-get update && apt-get install -y nano
These lines have been removed.

2022-02-25 22:26 UTC, dmccoystephenson commented on src/acm.cpp
> +    // std::cout << "The topic_available() method has finished executing. Return value: " << r << std::endl;
Removed.

2022-02-25 22:26 UTC, dmccoystephenson commented on src/acm.cpp
> +        // conf->set("debug", "all", error_string);
Removed.

2022-02-25 22:26 UTC, dmccoystephenson commented on src/acm.cpp
> +    // print_configuration();
Removed.

2022-02-28 14:37 UTC, drewjj approved these changes
Things look good, we will need to write some documentation on this. I plan to include the documentation in the ODE's wiki.  I will meet with you to go over that today.

2022-02-28 16:05 UTC, payneBrandon commented on docker-compose-confluent-cloud.yml
> +version: '2'
When we make the PR for the ODE main module, we'll include changed to that docker-compose file that will include these separated decode/encode with optional CC integration

2022-02-28 16:37 UTC, dmccoystephenson commented
A section on CC integration has been added to the README.

2022-02-28 22:04 UTC, dmccoystephenson commented
An image has been pushed to our cluster with these updates.

2022-03-02 17:38 UTC, payneBrandon approved these changes
Looks good to me. I added a `build_local.sh` script to allow running all the build commands locally easier. If you think that looks good, we can go ahead and merge.

2022-03-02 22:52 UTC, dmccoystephenson commented
Looks good to me!

2022-03-02 22:53 UTC, merged