Update j2735 version to 2024
CDOT-CV/asn1_codec pull request #35
Opened 2024-11-17 22:17 UTC by iyourshaw

Draft PR.  I will write more words here.

2024-11-18 22:15 UTC, dmccoystephenson requested changes

2024-11-18 22:15 UTC, dmccoystephenson commented on docker-compose-debug.yml
(non-blocking) Should we add some documentation regarding how this file should be used?

2024-11-18 22:54 UTC, dmccoystephenson requested changes

2024-11-18 22:54 UTC, dmccoystephenson commented on asn1c_combined/README.md
The `Installing asn1c` section should be updated to include the installation of dependent packages (gcc, autoconf, automake, libtool, bison, etc) using apt. Currently it takes some trial & error to get the tool installed.

2024-11-18 22:54 UTC, dmccoystephenson commented on Dockerfile.standalone
> +# RUN cd asn1c && test -f configure || autoreconf -iv && ./configure && make && make install
If we're removing the asn1c installation from the Dockerfiles we can probably get rid of some of the packages that are installed with apk like `bison` or `libtool`. Some experimentation may be necessary to identify which packages should be removed.

2024-11-18 23:38 UTC, dmccoystephenson requested changes

2024-11-18 23:38 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
> +if [ "$year" == "2024" ]; then
I'm running into the following in WSL when I execute this script:
```
./generate-files.sh: 28: [: 2024: unexpected operator
./generate-files.sh: 51: [: 2024: unexpected operator
```

2024-11-18 23:51 UTC, iyourshaw commented on asn1c_combined/generate-files.sh
> +if [ "$year" == "2024" ]; then
Weird.  I am also using WSL and it works for me.  That kind of error might happen if you were running "sh" instead of "bash" maybe.  What do you see if you do "bash --version"?  I have:

GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

2024-11-18 23:57 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
> +if [ "$year" == "2024" ]; then
I was using `sudo sh ./generate-files.sh`, that's probably why I ran into this. When I run `sudo bash ./generate-files.sh`, I see the following:
> Applying J2735 ASN Edits
patching file ./j2735-asn-files/2024/J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored
patching file ./j2735-asn-files/2024/J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored
(Stripping trailing CRs from patch; use --binary to disable.)
patching file ./j2735-asn-files/2024/J3217-TollUsageMsg-2024-rel-v1.1.asn
Hunk #1 FAILED at 157 (different line endings).
Hunk #2 FAILED at 184 (different line endings).
2 out of 2 hunks FAILED

I may just need to clean my environment though.

2024-11-19 00:02 UTC, iyourshaw commented on asn1c_combined/generate-files.sh
> +if [ "$year" == "2024" ]; then
Those errors are normal if the patch has already been done once

2024-11-19 00:30 UTC, iyourshaw commented on asn1c_combined/j2735-asn-files/2024/asn-edits/RoadUserChargingReportMessage.patch
Added some documentation for the .patch files

2024-11-19 00:53 UTC, iyourshaw commented on data/InputData.encoding.tim.odetimpayload.xml
> +<?xml version="1.0"?><OdeAsn1Data><metadata><request><ode><version>2</version></ode><sdw><serviceRegion><nwCorner><latitude>44.998459</latitude><longitude>-111.040817</longitude></nwCorner><seCorner>
Good point.  I think we should do that.  Although it is a sort of trivial change, it is nonetheless breaking and could be a sticking point for anyone who tries to use the XML encoding, so good to document in an obvious way.  I updated the Release Notes.

2024-11-19 19:59 UTC, iyourshaw commented on docker-compose-debug.yml
Added instructiond for using this docker compose file to `testing.md`

2024-11-19 20:19 UTC, iyourshaw commented on asn1c_combined/README.md
Added WSL instructions for installing prerequisites to README

2024-11-19 20:56 UTC, dmccoystephenson requested changes

2024-11-19 20:56 UTC, dmccoystephenson commented on asn1c_combined/README.md
> +#### Install Prerequesites
Looks like a typo here: 'Prerequesites" should be 'Prerequisites'

2024-11-19 20:56 UTC, dmccoystephenson commented on asn1c_combined/README.md
> +#### Run the asn1c Installation Script
I don't think we have an installation script, just the list of commands to run

2024-11-19 20:56 UTC, dmccoystephenson commented on docs/Release_notes.md
> +* CDOT PR 35: Update j24735 version to 2024.
Looks like a typo here: 'j24735' should be 'j2735'

2024-11-19 20:56 UTC, dmccoystephenson commented on docs/Release_notes.md
> +Version 3.0.0, Future Realase
Looks like a typo here: 'Realase' should be 'Release'

2024-11-19 20:56 UTC, dmccoystephenson commented on data/InputData.encoding.tim.odetimpayload.xml
> +<?xml version="1.0"?><OdeAsn1Data><metadata><request><ode><version>2</version></ode><sdw><serviceRegion><nwCorner><latitude>44.998459</latitude><longitude>-111.040817</longitude></nwCorner><seCorner>
Sounds good!

2024-11-19 20:57 UTC, dmccoystephenson commented on asn1c_combined/j2735-asn-files/2024/asn-edits/RoadUserChargingReportMessage.patch
Awesome thanks for doing that

2024-11-19 22:06 UTC, iyourshaw commented on asn1c_combined/README.md
> +#### Install Prerequesites
Fixed

2024-11-19 22:06 UTC, iyourshaw commented on asn1c_combined/README.md
> +#### Run the asn1c Installation Script
Fixed

2024-11-19 22:06 UTC, iyourshaw commented on docs/Release_notes.md
> +* CDOT PR 35: Update j24735 version to 2024.
Fixed.

2024-11-19 22:08 UTC, iyourshaw commented on docs/Release_notes.md
> +Version 3.0.0, Future Realase
Oh geez, my typing fingers need to have word with each other.  Fixed.

2024-11-19 22:31 UTC, iyourshaw commented on Dockerfile.standalone
> +# RUN cd asn1c && test -f configure || autoreconf -iv && ./configure && make && make install
I experimented with this and it seem that libtool, automake, autoconf, bison, and flex aren't needed on the build anymore, so updated the Dockerfiles accordingly.

2024-11-20 17:15 UTC, dmccoystephenson requested changes

2024-11-20 17:15 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
When running `sudo bash ./generate-files.sh` using WSL in the `asn1_combined` directory with a fresh clone, I see the following output:
```
Applying J2735 ASN Edits
patching file ./j2735-asn-files/2024/J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn
Hunk #1 FAILED at 136.
Hunk #2 FAILED at 141.
Hunk #3 FAILED at 222.
patch: **** Can't reopen file ./j2735-asn-files/2024/J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn : No such file or directory
patching file ./j2735-asn-files/2024/J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn
Hunk #1 FAILED at 98.
Hunk #2 FAILED at 144.
patch: **** Can't reopen file ./j2735-asn-files/2024/J3217-R-RoadUserChargingReportMsg-2024-rel-v1.1.asn : No such file or directory
(Stripping trailing CRs from patch; use --binary to disable.)
patching file ./j2735-asn-files/2024/J3217-TollUsageMsg-2024-rel-v1.1.asn
Hunk #1 FAILED at 157.
Hunk #2 FAILED at 184.
patch: **** Can't reopen file ./j2735-asn-files/2024/J3217-TollUsageMsg-2024-rel-v1.1.asn : No such file or directory

...

FATAL: Cannot find external module "TravelerInformation" mentioned for "MsgCRC" at line 143. Obtain this module and instruct compiler to process it too. in ./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn
FATAL: Unknown type "MsgCRC" referenced by "crc" at line 143 in ./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn
FATAL: Cannot find external module "TravelerInformation" mentioned for "MsgCRC" at line 136. Obtain this module and instruct compiler to process it too. in ./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn

...

Copying overrides for 2024
Tarring generated files for 2024
```

Looks like it can't find some of the files included in the J2735 2024 ASN files downloaded from the link in the README.

When extracting the contents of the JAR it only had the overrides:
![image](https://github.com/user-attachments/assets/d0596809-add7-4b8f-8e46-474abb532237)

It may be good to check for success and avoid generating the .tar file if the asn1c command fails.

2024-11-20 17:58 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
I just realized I had copied the ASN files for the 2023 revision. I will try again with the correct files.

2024-11-20 18:03 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
It is possible for the patches to fail due to "different line endings":
```
Hunk #1 FAILED at 157 (different line endings).
Hunk #2 FAILED at 184 (different line endings).
2 out of 2 hunks FAILED
```
We may want to specify that all files in the $year directory should have the 'LF' line ending.

2024-11-20 18:07 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
Alternatively I suppose the `generate-files.sh` script could ensure line endings are LF before applying the patch

2024-11-20 18:12 UTC, dmccoystephenson commented on asn1c_combined/generate-files.sh
Okay I got it to work by changing the line endings of the .patch files to LF.

2024-11-20 18:35 UTC, dmccoystephenson reviewed
This looks great! Here's what I’ve verified:
- The docker image can be built & spun up
- The unit tests pass
- The `do_kafka_test.sh` script runs successfully
- The `generate-asn.sh` script works and generate valid C

Additionally, I’ve confirmed that the dev branch of the jpo-ode repository is currently incompatible with these changes because it generates input XER for the AEM based on J2735 2020.

I’ll be creating a separate PR for the jpo-ode repository to update it to target J2735 2024. Until that PR is submitted and approved, we should hold off on merging this one.

2024-11-20 19:52 UTC, iyourshaw commented on asn1c_combined/generate-files.sh
I think git mangled those line endings.  Added a .gitattributes file to try to prevent that from happening.

2024-11-20 21:24 UTC, iyourshaw commented on asn1c_combined/generate-files.sh
Further update.  Setting the .patch files line endings to LF actually still gave me the same error, since the ASN files have CRLF line endings.  I updated it again with something that does seem to work, which is to force the patch files to have CRLF endings, and also add the --binary flag to the patch command, to prevent it from stripping the CRs off..

2024-12-11 20:13 UTC, payneBrandon commented on asn1c_combined/README.md
> +In the 2024 set of ASN files there are a couple changes that need to be made for them to compile with the current version of asn1c.  These changes are shown in the form of `.patch` files in the `j273
```suggestion
In the 2024 set of ASN files there are a couple changes that need to be made for them to compile with the current version of asn1c.  These changes are shown in the form of `.patch` files in the `j2735-asn-files/2024/asn-edits` directory.  The `.patch` files contain only the spcific lines in the specific files that need to be changed, due to the aforementioned prohibition on redistributing the ASN files.  The patches were created with the `diff` command line utility, and are applied automatically by the `generate-files.sh` script before it runs asn1c to compile the ASN files.  The `patch` command line in that script includes the `--forward` option, which prevents the patch from being reversed if the script is run more than once.
```

2024-12-11 20:19 UTC, payneBrandon commented on asn1c_combined/j2735-asn-files/2024/asn-edits/RoadUserChargingReportMessage.patch
> ++    vehicleID               TumVehicleId,         -- From J3217 TUM, EDITED
Is this "Tum" correct for the RoadUserChargingReportMessage? I see we did the same for TollUsageMessage which tum could be short for, but would this be better to be named "RucVehicleId" to match the class?

2024-12-11 20:29 UTC, payneBrandon commented on asn1c_combined/j2735-asn-files/2024/asn-edits/RoadUserChargingReportMessage.patch
> ++    vehicleID               TumVehicleId,         -- From J3217 TUM, EDITED
Ah, read the description more thoroughly and this appears to be changing an import for the previously renamed id. This makes more sense now

2024-12-11 20:29 UTC, iyourshaw commented on asn1c_combined/j2735-asn-files/2024/asn-edits/RoadUserChargingReportMessage.patch
> ++    vehicleID               TumVehicleId,         -- From J3217 TUM, EDITED
RoadUserChargingReportMessage imports 'VehicleId' from TollUsageMessage so it has to be the same to match:

```asn1
RoadUserChargingReportMessage 
{joint-iso-itu-t (2) country (16) us (840) organization (1) sae (114566) 
v2x-communications (1) technical-committees (1) tolling-applications (9) technical-reports (1) 
j3217 (3217) slash-r (28) asn1-module (1) roadUserChargingReportMessage (4) 
version-1 (1) version-minor-1 (1)}

DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

IMPORTS 
    VehicleTypes 
        FROM TollAdvertisementMessage {joint-iso-itu-t (2) country (16) us (840)
        organization (1) sae (114566) v2x-communications (1) technical-committees (1)
        tolling-applications (9) technical-reports (1) j3217 (3217) asn1-module (1)
        tollAdvertisementMessage (0) version-1 (1) version-minor-1 (1)} 
    VehicleId 
        FROM TollUsageMessage {joint-iso-itu-t (2) country (16) us (840)
        organization (1) sae (114566) v2x-communications (1) technical-committees (1)
        tolling-applications (9) technical-reports (1) j3217 (3217) asn1-module (1)
        tollUsageMessage (1) version-1 (1) version-minor-1 (1)} 
```

2024-12-11 21:40 UTC, payneBrandon requested changes
Just a couple questions/comments. Overall looks great!

2024-12-11 21:41 UTC, payneBrandon approved these changes
lgtm!

2024-12-11 21:43 UTC, merged