Simplified Logging + Log Level Env Var
CDOT-CV/asn1_codec pull request #9
Opened 2023-03-19 02:09 UTC by dmccoystephenson

## Simplified Logging
The AcmLogger class has been simplified to only use one spdlog logger (instead of separate info & error spdlog loggers).

## Log Level Env Var
The log level for the ACM is now passed in the `run_acm.sh` script via the ACM_LOG_LEVEL environment variable, which has been added to the docker-compose files for the project.

## Additional Changes
- A `sample.env` file has been added to the project.
- The `docker-compose.yml` file now uses `Dockerfile` instead of `Dockerfile.standalone` since the latter doesn't execute the program.
- The run_acm.sh script is now copied over to the image in the `Dockerfile.standalone` file.

## Verification
- Unit tests have been verified to pass in the provided dev container.
- Passing the log level via the env var has been verified to work with docker-compose locally.
- Passing the log level via the env var has been verified to work in our dev cluster.

2023-03-20 18:53 UTC, drewjj requested changes
Everything looks good, just one small detail and then I will approve

2023-03-20 18:53 UTC, drewjj commented on sample.env
> +ACM_LOG_LEVEL=
Can you specify the options here for the logging level. I am not certain if it is identical to Java's options but it would be helpful for someone who doesn't know.

2023-03-20 18:59 UTC, payneBrandon requested changes
Just the one comment, looks good!

2023-03-20 20:27 UTC, dmccoystephenson commented on src/acm_blob_producer.cpp
> +    acm_blob_producer.addOption('i', "ilog", "Information log file name.", true);
Nope! I've removed unnecessary references to ilog/elog, thanks for catching this!

2023-03-20 20:28 UTC, dmccoystephenson commented
Tested recent changes in our dev cluster and the logs look good! This is ready for re-review.

2023-03-24 22:17 UTC, payneBrandon approved these changes
Looks good to me!

2023-03-24 22:17 UTC, merged